name = "warkop"
type = "javascript"
account_id = "79acc6c68003ac9ef4666a7a5ccf8761"
workers_dev = true

[env.production]
workers_dev = false
route = "https://www.aep.my.id/*"
zone_id = "ea04b7d9d655c424ca4ccf1595000d43"

[site]
bucket = "./"
entry-point = "workers-site"
